spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/anything_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    defer-datasource-initialization: true # Hibernate 초기화를 통해 생성된 스키마에다가 데이터를 채우기를 위해서 data.sql가 실행
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  output:
    ansi:
      enabled: always

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.kenux.anything: debug

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-sample-kenux-spring-boot-security-jwt-sample' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNhbXBsZS1rZW51eC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2FtcGxlCg==

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/core_security_study_1
    username: kenux
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.diralect.PostgreSQL96Dialect
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true