spring:
  output: # console 에 색상 넣기
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/anything_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace