spring:
  output:
    ansi:
      enabled: always

  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/core_security_study

#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/h2dbs/anything_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      dialect: org.hibernate.diralect.PostgreSQL96Dialect
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.kenux.anything: info